"""Generate the landscape hardware diagram and matching hit bounds.

Reference: user's top view, keys left, OLED top-right, two knobs and large dial.
Encoder IDs remain logical IDs pending physical wiring confirmation.
"""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
controls=[]
svg=['''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 540">
<title>NovaKey landscape control layout</title>
<desc>Four by four keys on the left. Horizontal OLED above two small knobs on the right, with a large dial beneath them.</desc>
<defs>
<linearGradient id="case" x2="0" y2="1"><stop stop-color="#ed9b56"/><stop offset="1" stop-color="#b85f2d"/></linearGradient>
<linearGradient id="key" x2="0" y2="1"><stop stop-color="#e59757"/><stop offset="1" stop-color="#9d4d28"/></linearGradient>
</defs>
<path d="M 54 32 H 845 Q 872 32 872 60 V 325 Q 872 354 846 368 L 659 489 Q 635 506 605 506 H 54 Q 28 506 28 480 V 58 Q 28 32 54 32 Z" fill="#733e26" transform="translate(0 9)"/>
<path d="M 54 32 H 845 Q 872 32 872 60 V 325 Q 872 354 846 368 L 659 489 Q 635 506 605 506 H 54 Q 28 506 28 480 V 58 Q 28 32 54 32 Z" fill="url(#case)" stroke="#f2b074" stroke-width="2"/>
<rect x="726" y="6" width="48" height="26" rx="4" fill="#8b8984"/>
''']
def region(id,label,kind,x,y,w,h):
 controls.append(f"  ControlSpec(id: '{id}', label: '{label}', type: ControlType.{kind}, x: {x}, y: {y}, width: {w}, height: {h}),")
for row in range(4):
 for col in range(4):
  n=row*4+col+1;x=54+col*102;y=61+row*104
  svg.append(f'<rect id="key-{n:02}" x="{x}" y="{y}" width="94" height="96" rx="10" fill="url(#key)" stroke="#8d4628"/><rect x="{x+8}" y="{y+6}" width="78" height="77" rx="9" fill="#75452e" stroke="#eea366"/>')
  region(f'key-{n:02}',f'Key {n:02}','key',x,y,94,96)
for n,cx,cy,r in [(1,595,371,91),(2,520,215,35),(3,671,215,35)]:
 svg.append(f'<circle cx="{cx}" cy="{cy+4}" r="{r+5}" fill="#874727"/><circle id="enc-{n}-press" cx="{cx}" cy="{cy}" r="{r}" fill="#42352b"/><circle cx="{cx}" cy="{cy}" r="{r-7}" fill="#d38348" stroke="#eda262" stroke-width="2"/><path d="M {cx} {cy-r+13} v 12" stroke="#704329" stroke-width="3"/>')
 region(f'enc-{n}-press',f'Encoder {n} · Press','encoderPress',cx-r,cy-r,r*2,r*2)
 for suffix,dx,kind in [('ccw',-44,'encoderCounterClockwise'),('cw',4,'encoderClockwise')]:
  y=cy+r+8
  svg.append(f'<rect id="enc-{n}-{suffix}" x="{cx+dx}" y="{y}" width="40" height="27" rx="6" fill="#4d3829"/>')
  region(f'enc-{n}-{suffix}',f'Encoder {n} · '+('Clockwise' if suffix=='cw' else 'Counter-clockwise'),kind,cx+dx,y,40,27)
svg.append('''<rect x="484" y="61" width="235" height="100" rx="5" fill="#924a2a"/>
<rect x="493" y="69" width="217" height="84" rx="2" fill="#1b201b"/>
<path d="M 507 85 h 58 M 507 94 h 34" stroke="#cbff4a" stroke-width="2"/>
<path d="M 726 421 l 12 7 M 755 402 l 12 7 M 784 383 l 12 7 M 813 364 l 12 7" stroke="#844525" stroke-width="7"/>
<text x="755" y="113" fill="#75432b" font-family="sans-serif" font-size="11" letter-spacing="2">NOVAKEY</text>
</svg>''')
(ROOT/'assets/novakey-layout.svg').write_text('\n'.join(svg))
(ROOT/'lib/device/device_layout.dart').write_text("// Generated by tool/generate_layout.py; artwork and hit regions share coordinates.\nimport '../models/control_binding.dart';\n\nconst deviceWidth = 900.0;\nconst deviceHeight = 540.0;\n\nconst controls = <ControlSpec>[\n"+'\n'.join(controls)+'\n];\n')
