// Hit regions measured against assets/novakey_v3.png.
import '../models/control_binding.dart';

const deviceWidth = 1078.0;
const deviceHeight = 685.0;

const controls = <ControlSpec>[
  // Firmware protocol 3: canonical Key 01 at top-left, Key 16 at bottom-right.
  ControlSpec(
    id: 'key-01',
    label: 'Key 01',
    type: ControlType.key,
    x: 530,
    y: 117,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-02',
    label: 'Key 02',
    type: ControlType.key,
    x: 641,
    y: 117,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-03',
    label: 'Key 03',
    type: ControlType.key,
    x: 752,
    y: 117,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-04',
    label: 'Key 04',
    type: ControlType.key,
    x: 862,
    y: 117,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-05',
    label: 'Key 05',
    type: ControlType.key,
    x: 530,
    y: 228,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-06',
    label: 'Key 06',
    type: ControlType.key,
    x: 641,
    y: 228,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-07',
    label: 'Key 07',
    type: ControlType.key,
    x: 752,
    y: 228,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-08',
    label: 'Key 08',
    type: ControlType.key,
    x: 862,
    y: 228,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-09',
    label: 'Key 09',
    type: ControlType.key,
    x: 530,
    y: 338,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-10',
    label: 'Key 10',
    type: ControlType.key,
    x: 641,
    y: 338,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-11',
    label: 'Key 11',
    type: ControlType.key,
    x: 752,
    y: 338,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-12',
    label: 'Key 12',
    type: ControlType.key,
    x: 862,
    y: 338,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-13',
    label: 'Key 13',
    type: ControlType.key,
    x: 530,
    y: 449,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-14',
    label: 'Key 14',
    type: ControlType.key,
    x: 641,
    y: 449,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-15',
    label: 'Key 15',
    type: ControlType.key,
    x: 752,
    y: 449,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'key-16',
    label: 'Key 16',
    type: ControlType.key,
    x: 862,
    y: 449,
    width: 109,
    height: 109,
  ),
  ControlSpec(
    id: 'enc-1-press',
    label: 'Encoder 1 · Press',
    type: ControlType.encoderPress,
    x: 298,
    y: 164,
    width: 190,
    height: 190,
  ),
  ControlSpec(
    id: 'enc-1-ccw',
    label: 'Encoder 1 · Counter-clockwise',
    type: ControlType.encoderCounterClockwise,
    x: 352,
    y: 344,
    width: 38,
    height: 28,
  ),
  ControlSpec(
    id: 'enc-1-cw',
    label: 'Encoder 1 · Clockwise',
    type: ControlType.encoderClockwise,
    x: 398,
    y: 344,
    width: 38,
    height: 28,
  ),
  ControlSpec(
    id: 'enc-2-press',
    label: 'Encoder 2 · Press',
    type: ControlType.encoderPress,
    x: 406,
    y: 369,
    width: 97,
    height: 97,
  ),
  ControlSpec(
    id: 'enc-2-ccw',
    label: 'Encoder 2 · Counter-clockwise',
    type: ControlType.encoderCounterClockwise,
    x: 416,
    y: 466,
    width: 36,
    height: 27,
  ),
  ControlSpec(
    id: 'enc-2-cw',
    label: 'Encoder 2 · Clockwise',
    type: ControlType.encoderClockwise,
    x: 458,
    y: 466,
    width: 36,
    height: 27,
  ),
  ControlSpec(
    id: 'enc-3-press',
    label: 'Encoder 3 · Press',
    type: ControlType.encoderPress,
    x: 284,
    y: 369,
    width: 97,
    height: 97,
  ),
  ControlSpec(
    id: 'enc-3-ccw',
    label: 'Encoder 3 · Counter-clockwise',
    type: ControlType.encoderCounterClockwise,
    x: 294,
    y: 466,
    width: 36,
    height: 27,
  ),
  ControlSpec(
    id: 'enc-3-cw',
    label: 'Encoder 3 · Clockwise',
    type: ControlType.encoderClockwise,
    x: 336,
    y: 466,
    width: 36,
    height: 27,
  ),
];
