// Firmware protocol 3 canonical control IDs, independent of UI list order.
const protocolControlIds = <String>[
  'key-01',
  'key-02',
  'key-03',
  'key-04',
  'key-05',
  'key-06',
  'key-07',
  'key-08',
  'key-09',
  'key-10',
  'key-11',
  'key-12',
  'key-13',
  'key-14',
  'key-15',
  'key-16',
  'enc-1-press',
  'enc-1-ccw',
  'enc-1-cw',
  'enc-2-press',
  'enc-2-ccw',
  'enc-2-cw',
  'enc-3-press',
  'enc-3-ccw',
  'enc-3-cw',
];
